apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow
spec:
  selector:
    matchLabels:
      app: yellow
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
      - name: yellow
        image: kangdaeyoung/keduit:jktest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
spec:
  selector:
    app: yellow
  ports:
  - port:  80
    targetPort:  80
  type: LoadBalancer
